server {
    listen 80;
    server_name _;

    location /privacy {
        alias /usr/share/nginx/html/privacy.html;
        default_type text/html;
    }

    location = / {
        return 302 /privacy;
    }
}
